stages:
  - build

npm:
  image: node
  stage: build
  before_script:
    - node -v
  script:
    - ./scripts/build/ui.sh
  tags:
    - docker

docker:
  image: docker
  stage: build
  services:
    - docker:dind
  before_script:
    - cp env/ci .env
    - apk add --update py-pip
    - pip install docker-compose
    - docker -v
    - docker-compose -v
    - docker login -u $DOCKER_REPOSITORY_USERNAME -p $DOCKER_REPOSITORY_PASSWORD
  script:
    - docker-compose build
    - docker-compose push
  tags:
    - docker

