stages:
  - build

npm:
  image: node
  stage: build
  before_script:
    - node -v
  script:
    - ./scripts/build/ui.sh
  tags:
    - docker

docker:
  image: docker
  stage: build
  services:
    - docker:dind
  before_script:
    - ./scripts/setup/env.sh ci
    - apk add --update py-pip
    - pip install docker-compose
    - docker -v
    - docker-compose -v
  script:
    - docker-compose build
  tags:
    - docker

