sudo: required

env:
  global:
    - ENV_FILE="ci"

services:
  - docker

jobs:
  include:
    - stage: build
      language: node_js
      node_js:
        - "8"
      script: ./scripts/build/ui.sh
    -
      script: cp "env/$ENV_FILE" .env && docker-compose build
