sudo: required

env:
  global:
    - ENV_FILE="ci"

services:
  - docker

jobs:
  include:
    - stage: build
      language: node_js
      script: ./build/ui.sh
    -
      script: cp "env/$ENV_FILE" .env && docker-compose build
