version: "2.0"

volumes:
  secrets:

services:
  ui:
    image: instanalizer/ui
    build: ui
    ports:
      - 8080:80
    volumes:
      - ./ui:/app

  authentication:
    image: php:${PHP_VERSION}
    command: php -S 0.0.0.0:80 -t /app/public
    ports:
      - 8082:80
    volumes:
      - ./authentication:/app

  api-gateway:
    image: webdevops/php-nginx-dev:${PHP_VERSION}
    volumes:
      - ./services/api-gateway:/app
    ports:
      - 8081:80

  secret-simulator:
      image: mikesir87/secrets-simulator
      volumes:
        - secrets:/run/secrets:rw
