version: "2.0"

volumes:
  secrets:

services:
  ui:
    image: instanalizer/ui
    build: ui
    ports:
      - 8080:80
    volumes:
      - ./ui:/app

  authentication:
    ports:
      - 8082:80
    volumes:
      - ./services/authentication:/app

  api-gateway:
    ports:
      - 8081:80
    volumes:
      - ./services/api-gateway:/app

  secret-simulator:
      image: mikesir87/secrets-simulator
      volumes:
        - secrets:/run/secrets:rw
