branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: twitter-media-downloader
  default_ec2_keyname: null
  default_platform: PHP 7.0
  default_region: eu-west-2
  profile: eb-cli
  sc: null
