branch-defaults:
  master:
    environment: prod
global:
  application_name: instanalizer
  branch: master
  default_ec2_keyname: eb
  default_platform: Multi-container Docker 1.12.6 (Generic)
  default_region: eu-west-2
  sc: git
  workspace_type: Application
